import assert from "node:assert/strict";
import { promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { executeRemoteSetup, type RemoteSetupEngineDependencies } from "../src/setup/engine.js";
import type { SetupPresenter } from "../src/setup/presentation.js";
import type { RemoteSetupConfig, RemoteSetupPlan } from "../src/setup/remote.js";
import type { DesiredRemoteState, InstalledRemoteState, RemoteStateComparison, RemoteSetupChangeType } from "../src/setup/state.js";

interface Calls { preflight: number; install: number; trust: number; synchronize: number; certify: number; rollback: number }
function desired(): DesiredRemoteState { return { schemaVersion: 2, sourceSha: "1".repeat(40), dispatcherMode: "controlled", runtimeSha256: "2".repeat(64), dispatcherSha256: "3".repeat(64), policySha256: "4".repeat(64), capabilityIdentitySha256: "5".repeat(64), declarationSha256: "6".repeat(64), operatorVerificationIdentity: "7".repeat(64), applicationScope: ["app.sample-api"], applicationScopeSha256: "8".repeat(64) }; }
function installed(expected: DesiredRemoteState): InstalledRemoteState { return { status: "complete", source: "installed remote state", schemaVersion: 2, generation: 1, sourceSha: expected.sourceSha, dispatcherMode: expected.dispatcherMode, runtimeSha256: expected.runtimeSha256, dispatcherSha256: expected.dispatcherSha256, policySha256: expected.policySha256, capabilityIdentitySha256: expected.capabilityIdentitySha256, capabilityArtifactSha256: "9".repeat(64), declarationSha256: expected.declarationSha256, operatorVerificationIdentity: expected.operatorVerificationIdentity, applicationScope: expected.applicationScope, applicationScopeSha256: expected.applicationScopeSha256, platform: "Linux", architecture: "x86_64" }; }
function comparison(): RemoteStateComparison { const expected = desired(); return { desired: expected, installed: installed(expected), changeType: "NO_CHANGE", reasons: [], compatible: true }; }
async function fixture(): Promise<{ root: string; config: RemoteSetupConfig }> { const root = await fs.mkdtemp(path.join(tmpdir(), "opshaven-fast-setup-")); return { root, config: { version: 1, policyConfigPath: path.join(root, "config.json"), expectedSourceSha: "1".repeat(40), target: { host: "example.invalid", port: 22, adminUser: "root", knownHostsFile: path.join(root, "known_hosts"), identityFile: path.join(root, "identity"), expectedHostKeySha256: "SHA256:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", privilege: "root" }, local: { runtimeRoot: path.join(root, "dist"), dispatcherPath: path.join(root, "dist/src/remote/dispatcher.js"), wrapperTemplatePath: path.join(root, "wrapper"), capabilityDeclarationPath: path.join(root, "declaration.json"), operatorPrivateKeyFile: path.join(root, "private.pem"), operatorPublicKeyFile: path.join(root, "public.pem"), restrictedAuthorizedKeyFile: path.join(root, "restricted.pub") }, remote: { account: "opshaven", runtimeRoot: "/usr/lib/opshaven", configPath: "/etc/opshaven/config.json", wrapperPath: "/usr/local/bin/opshaven-readonly-force-command", stateDirectory: "/var/lib/opshaven", receiptPath: "/var/lib/opshaven/setup-receipt.json", nodeCandidates: ["/usr/bin/node"] }, trust: { expiresInSeconds: 3600 } } }; }
function plan(changeType: RemoteSetupChangeType): RemoteSetupPlan { return { version: 1, sourceSha: "1".repeat(40), target: "root@example.invalid:22", changeType, changes: [], estimatedDuration: "fixture", mutations: [] }; }
function presenter(): SetupPresenter { return { plan: () => undefined, step: () => undefined, progress: () => undefined, cancellation: () => undefined, fingerprint: () => undefined, approve: async () => true, receipt: () => undefined }; }
function dependencies(calls: Calls, controller?: AbortController): RemoteSetupEngineDependencies { return { preflight: async () => { calls.preflight += 1; return { ok: true, checkedAt: new Date().toISOString(), nodePath: "/usr/bin/node", remote: { platform: "Linux", distribution: "ubuntu", version: "24.04", architecture: "x86_64", nodePath: "/usr/bin/node", nodeVersion: "v22.0.0", freeBytes: 999999999, installation: { accountExists: true, runtimeExists: true, wrapperExists: true, configExists: true, receiptExists: true } }, checks: [] }; }, install: async () => { calls.install += 1; return { ok: true, changed: [], runtimeTreeSha256: "2".repeat(64), backupRoot: "/var/lib/opshaven/backups/runtimefixture", receiptId: "runtimefixture" }; }, trust: async () => { calls.trust += 1; return { ok: true, mode: "controlled", synchronizationKind: "runtime-install", receiptId: "runtimefixture", backupRoot: "/var/lib/opshaven/backups/runtimefixture", dispatcherSha256: "3".repeat(64), capabilitySha256: "a".repeat(64), declarationSha256: "6".repeat(64), bindingSha256: "b".repeat(64), responsePublicKeySha256: "c".repeat(64), expiresAt: new Date(Date.now() + 60000).toISOString(), installedPaths: [], changed: [] }; }, synchronize: async () => { calls.synchronize += 1; controller?.abort(); return { ok: true, mode: "controlled", synchronizationKind: "authorization-sync", receiptId: "syncfixture", backupRoot: "/var/lib/opshaven/backups/syncfixture", dispatcherSha256: "3".repeat(64), capabilitySha256: "a".repeat(64), declarationSha256: "6".repeat(64), bindingSha256: "b".repeat(64), responsePublicKeySha256: "c".repeat(64), expiresAt: new Date(Date.now() + 60000).toISOString(), installedPaths: [], changed: ["/etc/opshaven/config.json.capability.json"] }; }, certify: async () => { calls.certify += 1; return { ok: true, certifiedAt: new Date().toISOString(), boundarySha256: "d".repeat(64), assertions: [] }; }, rollback: async () => { calls.rollback += 1; return { ok: true, action: "rollback", completedAt: new Date().toISOString(), restored: ["/etc/opshaven/config.json.capability.json"], removed: [], preserved: [] }; }, desired: async () => desired(), readiness: async () => comparison(), verifyReadiness: async () => comparison() }; }
const zero = (): Calls => ({ preflight: 0, install: 0, trust: 0, synchronize: 0, certify: 0, rollback: 0 });

test("no-change setup performs no runtime or authorization mutation but still verifies", async () => { const value = await fixture(); const calls = zero(); try { const receipt = await executeRemoteSetup(value.config, plan("NO_CHANGE"), { approved: false, nonInteractive: true, tui: false, json: true, presenter: presenter(), dependencies: dependencies(calls) }); assert.equal(receipt.changeType, "NO_CHANGE"); assert.deepEqual(calls, { ...zero(), certify: 1 }); } finally { await fs.rm(value.root, { recursive: true, force: true }); } });
test("authorization-only setup reuses runtime and updates only signed state", async () => { const value = await fixture(); const calls = zero(); try { const receipt = await executeRemoteSetup(value.config, plan("AUTHORIZATION_ONLY"), { approved: true, nonInteractive: true, tui: false, json: true, presenter: presenter(), dependencies: dependencies(calls) }); assert.equal(receipt.changeType, "AUTHORIZATION_ONLY"); assert.equal(receipt.installation, undefined); assert.equal(receipt.trust?.synchronizationKind, "authorization-sync"); assert.deepEqual(calls, { ...zero(), synchronize: 1, certify: 1 }); } finally { await fs.rm(value.root, { recursive: true, force: true }); } });
test("cancellation after authorization mutation rolls back at the next atomic checkpoint", async () => { const value = await fixture(); const calls = zero(); const controller = new AbortController(); try { await assert.rejects(executeRemoteSetup(value.config, plan("AUTHORIZATION_ONLY"), { approved: true, nonInteractive: true, tui: false, json: true, presenter: presenter(), dependencies: dependencies(calls, controller), signal: controller.signal }), /cancellation was requested/); assert.equal(calls.synchronize, 1); assert.equal(calls.rollback, 1); assert.equal(calls.certify, 0); } finally { await fs.rm(value.root, { recursive: true, force: true }); } });
