import type { OpsHavenConfig } from "../config/schema.js";

export function renderSudoers(config: OpsHavenConfig, account = "opshaven"): string {
  const commands = new Set<string>();
  for (const service of config.services) {
    if (service.restartAllowed) commands.add(`/usr/bin/systemctl restart ${service.unit}`);
  }
  for (const deployment of config.deployments) {
    if (deployment.strategy === "systemd") {
      for (const serviceId of deployment.serviceIds) {
        const service = config.services.find((item) => item.id === serviceId);
        if (service !== undefined) commands.add(`/usr/bin/systemctl restart ${service.unit}`);
      }
    } else {
      commands.add(
        `/usr/bin/docker compose --project-directory ${deployment.activeSymlink} up -d --remove-orphans`
      );
    }
  }
  const lines = [
    "# Generated by OpsHaven. Review before installation.",
    "# No wildcards are used; regenerate after configuration changes.",
    ...[...commands].sort().map((command) => `${account} ALL=(root) NOPASSWD: ${command}`)
  ];
  return `${lines.join("\n")}\n`;
}
